### PR TITLE
Suggestions made

### PR DESCRIPTION
**Pull request by icarusgk**
## Description of Problem
The issues described here: #1 This PR aims to solve these.

## Proposed Solution
- Link back to the English docs
- Translate the Newsletters section
- Revert back all of header anchors to English

## Additional Information
I did a commit for each file changed on the first two elements in the list above, but when reverting all header anchors I'll do a commit that encapsulates all of those files.

### CODE REVIEW

**Comment by icarusgk** [comment]
I did a little Ruby script that takes the anchor headers from the english repo markdown files and adds or replaces the ones on the repo being translated, the Spanish one in this case. https://github.com/icarusgk/anchor-linking-script.

**Comment by icarusgk** [comment]
@drfcozapata Here's a PR with the changes mentioned on the discussion, please review it.

**Comment by glopzel** [comment]
Great job with the ruby script to change the header anchors, LGTM

**Comment by icarusgk** [comment]
Thank you! 😄

**Comment by drfcozapata** [comment]
No revisé... Estoy aceptando el pull request, pero ya ustedes revisarán. 
Mucho éxito brothers!

**Pull request merged**
